---
- name: Diagnose Image Pull BackOff Pod
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Find ImagePullBackOff pods
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: "{{ target_namespace }}"
      register: pod_info

    - name: Display ImagePullBackOff pods
      ansible.builtin.debug:
        msg: "IMAGE PULL ERROR : {{ item.metadata.name }}"
      loop: "{{ pod_info.resources }}"
      when:
        - item.status.containerStatuses is defined
        - item.status.containerStatuses | selectattr("state.waiting.reason", "defined") | selectattr("state.waiting.reason", "equalto", "ImagePullBackOff") | list | length > 0

    - name: No ImagePullBackOff pods found
      ansible.builtin.debug:
        msg: "No ImagePullBackOff pods found in {{ target_namespace }}"
      when: >
        pod_info.resources
        | selectattr("status.containerStatuses", "defined")
        | selectattr("status.containerStatuses", "selectattr", "state.waiting.reason", "defined")
        | list
        | length == 0
