---
- name: Diagnose Image Pull BackOff Pod
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Find ImagePullBackOff pods
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: "{{ target_namespace }}"
      register: pods

    - name: Display ImagePullBackOff pods
      ansible.builtin.debug:
        msg: >-
          {{ item.metadata.name }}
      loop: "{{ pods.resources }}"
      when: >
        item.status.containerStatuses is defined and
        (
          item.status.containerStatuses
          | selectattr('state.waiting', 'defined')
          | selectattr('state.waiting.reason', 'equalto', 'ImagePullBackOff')
          | list
          | length
        ) > 0
